name: Makefile CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup poetry
      uses: abatilo/actions-poetry@v2
    
    - name: Install dependencies
      run: make install