name: Makefile CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup poetry
      uses: abatilo/actions-poetry@v2
    
    - name: Install dependencies
      run: make install

    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1

    - name: Run lint
      run: make lint
